# Generated by Django 5.2.9 on 2025-12-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_spiritanimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('person', models.ManyToManyField(related_name='places_visited', to='main.person')),
            ],
        ),
    ]
